logger_dir : './runs'
data_path : './data'
data_name : 'hico'
thresh_file : 'thresh_precision_0.3'

optimizer : 'adam'
num_epochs : 11
lr_update : 11
learning_rate : 0.001
save_epoch : 5
num_workers : 8


train_split : 'trainval'
test_split : 'test'


network : 'netindepemb'
embed_size : 1024
d_hidden : 1024
num_layers : 2
sampler : 'priority_object'

exp_name : 'hico_trainval_base'

add_gt : True
net_unigram_s : 'appearanceprecompsubject'
net_unigram_o : 'appearanceprecompobject'
net_unigram_r : 'spatialappearanceprecomp'
net_trigram_sro : 'spatialappearanceprecomp'


net_language : 'word2vec_compositional_2fc'
criterion_name : 'logloss'

use_ram : True
use_precompappearance : True
num_negatives : 3

normalize_vis : False
normalize_lang : True
l2norm_input : True

# Test options
mixture_keys : 's-r-o_s-sro-o_s-r-o-sro'
cand_test : 'candidates'
sample_negatives : 'among_vocab'
nms_thresh : 0.3
epoch_model : 'epoch10'
